### PR TITLE
A bunch of fixes for api version 5.131

### PR DESCRIPTION
**Pull request by acceptTheVoid**
I may have added unnecessary Optional fields, it's really hard to test

### CODE REVIEW

**Comment by awaitlink** [comment]
> I may have added unnecessary Optional fields, it's really hard to test

I understand that due to the state of the documentation, it's hard to accurately determine whether something is optional or sometimes even the type. So thanks for testing this!

It's ok that some things are optional even though they might not have to be, I think it's better to explicitly let the library users handle them rather than getting deserialization issues.

---

As indicated by

https://github.com/u32i64/rvk/blob/4013e52500db5d27198796199387f6aec520c304/src/lib.rs#L48

this crate currently only supports version `5.103`.

If these changes should work with with `5.103` too (i.e. no deserialization issues regarding the new non-optional fields), I'm ok with merging this as is. However, in the other case, it's probably better to edit that line as well to say `5.131`.

Ideally, the crate should be fully updated by adding/removing any methods and objects according to the changelog from `5.103` to `5.131`, not just by changing objects. However, unfortunately, I have no intention of doing this myself in the near future. I would appreciate if you could look at whether that would involve a lot of changes or not.

If it's a lot of changes, I wonder if it would make sense to perhaps split this crate into something like:

- `rvk-methods` (will depend on `rvk` to call methods with a specific API version that it supports);
- `rvk-objects` (just providing the objects for a specific API version that it supports);
- `rvk` (just handling the interaction with the API, would be able to use any API version).

That way it would be possible to have `rvk-methods` and `rvk-objects` support different versions. As far as I understand, you (and potentially other contributors to this crate) might be using it this way anyway (just the objects), so it may be better to not have to pull in unnecessary dependencies and compile them.

Something easier to do but useful might also be to just add a function that creates an API client with any specified version (perhaps with a warning in documentation that the crate isn't guaranteed to support it).

Any thoughts on any of this?

**Comment by acceptTheVoid** [comment]
I would like to look into changelog and update this library accordingly, but I don't have enought time right now, so I'm focusing currently on parts of library that are needed for my specific usecase (getting posts from groups). 

I think that split crate is a good idea and it will allow more people create their own bindings without the annoying part of finding out what to put in your objects, so i'm on it. Though it will be a big task to change objects for multiple VK API versions.

It will be pretty good idea to create function that wraps around all of it, though it would make sense to split crate first and then get to it.

**Comment by awaitlink** [comment]
> I think that split crate is a good idea and it will allow more people create their own bindings without the annoying part of finding out what to put in your objects, so i'm on it.

Just to make sure I'm understanding correctly: will you do the split (and change this PR / make a new one)? Or should I split the crate? If you're doing it, let me know if you have any questions.

> Though it will be a big task to change objects for multiple VK API versions.

To be clear, I'm not suggesting that `rvk-objects` would support different API versions at the same time. Each version of the `rvk-objects` crate would support one specific version of the API. The benefits of splitting would be:

- It would be possible to update `rvk-objects` to support latest API versions while keeping `rvk-methods` intact. It's technically possible already, but it would be inconsistent because the crate as a whole declares support for a specific version. With split crates `rvk-objects` and `rvk-methods` would each have a separate supported version.
- No need to compile some crates if you're not using them.

---

> It will be pretty good idea to create function that wraps around all of it, though it would make sense to split crate first and then get to it.

I'm not sure what you mean by "function that wraps around all of it" here. Are you referring to the following?

> Something easier to do but useful might also be to just add a function that creates an API client with any specified version (perhaps with a warning in documentation that the crate isn't guaranteed to support it).

What I meant there is just to add an `api_version: String` field to `APIClient`, change the existing `new` function to use the default version and add a function that initializes it with a custom version, something like:

```rust
pub fn with_api_version(api_version: impl Into<String>, token: impl Into<String>) -> APIClient {
    APIClient {
        client: Client::new(),
        api_version: api_version.into(),
        token: token.into(),
    }
}
```

But this in itself shouldn't require splitting the crate. Although in case of split crates, since `rvk` wouldn't contain anything version-specific, it might as well only have the `with_api_version` function, perhaps named `new` like before. `rvk-methods` could provide a convenience function that initializes `rvk::APIClient` with the version that `rvk-methods` supports.

---

We should probably bump the edition to `2021` as well since we're "renovating" the crate?

https://github.com/u32i64/rvk/blob/4013e52500db5d27198796199387f6aec520c304/Cargo.toml#L11

**Comment by acceptTheVoid** [comment]
> Just to make sure I'm understanding correctly: will you do the split (and change this PR / make a new one)? Or should I split the crate? If you're doing it, let me know if you have any questions.

It's probably better for you to split it, if you have time for that.

> To be clear, I'm not suggesting that `rvk-objects` would support different API versions at the same time. Each version of the `rvk-objects` crate would support one specific version of the API.

That would actually make more sense. Should their versions be named accordingly to versions of VK API that they support? 

> But this in itself shouldn't require splitting the crate. Although in case of split crates, since `rvk` wouldn't contain anything version-specific, it might as well only have the `with_api_version` function, perhaps named `new` like before. `rvk-methods` could provide a convenience function that initializes `rvk::APIClient` with the version that `rvk-methods` supports.

Yeah I was referring to that. It will be more convinient to have a wrapper like this.

> We should probably bump the edition to `2021` as well since we're "renovating" the crate?

I agree. I hope it won't break anything.

Thank you for spending time for updating this crate. I'm not very experienced with rust and I'm currently learning all of it in two weeks, so I can't make api bindings as convinient as your crate, so than you for that! :)

**Comment by awaitlink** [comment]
> It's probably better for you to split it, if you have time for that.

Ok, I'll do it, hopefully soon.

> > To be clear, I'm not suggesting that rvk-objects would support different API versions at the same time. Each version of the rvk-objects crate would support one specific version of the API.
>
> That would actually make more sense. Should their versions be named accordingly to versions of VK API that they support?

I did think about doing this, but there is an issue: crates should generally follow [SemVer](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility). Something like `5.131.0` theoretically works, but the issue is that I can't guarantee absolute compatibility with that API version, so it may be necessary to add corrections (such as the ones you did) over time without changing the API version; and `5.131.x` is generally assumed to be compatible with `5.131.0` without any changes (whereas in this case there could be breaking changes such as changing struct fields, etc.).

It's possible to still go that way and add instructions to the README to use versions like `=5.131.0` to ensure that library users won't be unintentionally upgraded to an incompatible version, though I feel like matching common expectations is better.

Using something like `5131.0.0` is possible too but that could cause issues if VK decides to use 4 digits in the last version number (e.g. `5.1234` -> `51234.0.0`) and later changes back to less digits (e.g. `6.123` -> `6123.0.0`, which is less than `51234.0.0` but newer), etc. It's all possible to circumvent but that feels like a hack.

**Review by awaitlink — APPROVED** [review]
I'll merge this PR now to avoid extra conflicts/merging after the crate is split.

**Comment by awaitlink** [comment]
As an update, I've split the crate. See [the README](https://github.com/u32i64/rvk#readme) for usage. I've decided to use `_` instead of `-` in the crate names so that they're the same in both `Cargo.toml` and Rust code.

The changes from this PR are now available in [`rvk_objects`](https://crates.io/crates/rvk_objects) `0.1.0`.

> I'm not very experienced with rust and I'm currently learning all of it in two weeks, so I can't make api bindings as convinient as your crate, so than you for that! :)

Good luck on your learning! Glad my crate helps 🙂

**Pull request merged**
